import React, { useCallback, useEffect, useMemo, useState } from "react";
import "./video.css";

async function api(path, options = {}) {
  const response = await fetch(path, { credentials: "same-origin", headers: { "Content-Type": "application/json", ...(options.headers || {}) }, ...options });
  if (!response.ok) { const data = await response.json().catch(() => ({})); throw new Error(data.detail || `Ошибка ${response.status}`); }
  return response.json();
}

const duration = (seconds) => seconds ? `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}` : "—";
const providerLabel = { rutube: "RUTUBE", youtube: "YouTube", file: "Файл", link: "Ссылка" };

export function VideoAdmin() {
  const [tab, setTab] = useState("catalog"), [data, setData] = useState({ collections: [], videos: [] });
  const [sources, setSources] = useState([]), [selected, setSelected] = useState(null), [busy, setBusy] = useState(true), [error, setError] = useState("");
  const load = useCallback(async () => { setBusy(true); setError(""); try { const [library, sourceRows] = await Promise.all([api("/api/v53/videos/admin"), api("/api/v53/videos/sources")]); setData(library); setSources(sourceRows); } catch (e) { setError(e.message); } finally { setBusy(false); } }, []);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { const handler = (event) => { if (event.origin === window.location.origin && event.data?.type === "rtm-video-source-connected") load(); }; window.addEventListener("message", handler); return () => window.removeEventListener("message", handler); }, [load]);
  const collectionMap = useMemo(() => Object.fromEntries(data.collections.map((item) => [item.id, item])), [data.collections]);
  const addVideo = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); setError(""); try { await api("/api/v53/videos", { method: "POST", body: JSON.stringify({ title: form.get("title"), url: form.get("url"), collectionId: form.get("collectionId") ? Number(form.get("collectionId")) : null, status: "published" }) }); event.currentTarget.reset(); setSelected(null); await load(); } catch (e) { setError(e.message); } };
  const addCollection = async () => { const title = window.prompt("Название папки видеотеки"); if (!title?.trim()) return; await api("/api/v53/videos/collections", { method: "POST", body: JSON.stringify({ title }) }); await load(); };
  const connectYouTube = async () => { try { const result = await api("/api/v53/videos/sources/youtube/connect", { method: "POST", body: "{}" }); window.open(result.authorizationUrl, "rtm-youtube-oauth", "width=620,height=760"); } catch (e) { setError(e.message); } };
  return <section className="video-admin">
    <header className="video-admin-head"><div><span className="va-eyebrow">Медиа и контент</span><h1>Видеотека</h1><p>Коллекции обучающих видео и источники публикации.</p></div><button className="va-primary" onClick={() => setSelected({})}>Добавить видео</button></header>
    <nav className="va-tabs" aria-label="Разделы видеотеки">{[["catalog","Видео"],["collections","Коллекции и категории"],["sources","Настройки источников видео"]].map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
    {tab === "sources" && sources.some((source) => source.provider === "youtube" && source.configured) && <div className="va-source-actions"><button className="va-secondary" onClick={connectYouTube}>{sources.find((source) => source.provider === "youtube")?.connected ? "Переподключить YouTube" : "Подключить YouTube"}</button></div>}
    {error && <div className="va-alert" role="alert">{error}<button onClick={load}>Повторить</button></div>}
    {busy ? <div className="va-loading">Загружаем видеотеку…</div> : tab === "sources" ? <div className="va-source-list">{sources.map((source)=><article className="va-source" key={source.provider}><div className={`va-provider ${source.provider}`}>{source.provider === "file" ? "▣" : source.title}</div><div><h2>{source.title}</h2><span className={`va-status ${source.connected?"ok":"off"}`}>{source.connected?"Подключено":"Не подключено"}</span><p>{source.connected ? source.accountName || "Подключённый аккаунт" : source.provider === "file" ? "Собственное хранилище активно" : "Подключение появится после настройки OAuth на сервере"}</p></div><dl><div><dt>Видео в каталоге</dt><dd>{source.videoCount}</dd></div><div><dt>Последняя синхронизация</dt><dd>{source.lastSyncAt ? new Date(source.lastSyncAt).toLocaleString("ru-RU") : "Ещё не выполнялась"}</dd></div></dl><button disabled={!source.configured || source.provider === "file"}>{source.configured?"Настроить":"Нужна конфигурация сервера"}</button></article>)}</div> : tab === "collections" ? <div className="va-collection-page"><button className="va-secondary" onClick={addCollection}>+ Новая коллекция</button><div className="va-collection-grid">{data.collections.map((item)=><article key={item.id} style={{"--folder-accent":item.appearance?.accent || "#e57a00"}}>{item.coverUrl?<img src={item.coverUrl} alt=""/>:<span>▱</span>}<div><h2>{item.title}</h2><p>{item.description || "Описание не добавлено"}</p><small>{item.videoCount} видео · {item.visibility === "all" ? "для всех" : "ограниченный доступ"}</small></div></article>)}</div></div> : <div className="va-catalog"><aside><header><b>Коллекции</b><button onClick={addCollection}>+</button></header><button className="active">Все видео <span>{data.videos.length}</span></button>{data.collections.map((item)=><button key={item.id}>{item.title}<span>{item.videoCount}</span></button>)}</aside><div className="va-table-wrap"><div className="va-toolbar"><input aria-label="Поиск видео" placeholder="Поиск по названию"/><select aria-label="Статус"><option>Все статусы</option></select></div><table><thead><tr><th>Видео</th><th>Коллекция</th><th>Источник</th><th>Длительность</th><th>Статус</th></tr></thead><tbody>{data.videos.map((video)=><tr key={video.id}><td><button className="va-video-title" onClick={()=>setSelected(video)}>{video.thumbnailUrl?<img src={video.thumbnailUrl} alt=""/>:<span>{providerLabel[video.provider]}</span>}<b>{video.title}</b></button></td><td>{collectionMap[video.collectionId]?.title || "Без коллекции"}</td><td>{providerLabel[video.provider]}</td><td>{duration(video.durationSeconds)}</td><td><span className={`va-status ${video.status === "published"?"ok":"off"}`}>{video.status === "published"?"Опубликовано":"Черновик"}</span></td></tr>)}</tbody></table>{!data.videos.length&&<div className="va-empty"><b>Добавьте первое видео</b><span>RUTUBE, YouTube или прямая ссылка на видеофайл.</span></div>}</div></div>}
    {selected && <div className="va-drawer-scrim" onMouseDown={(e)=>e.target===e.currentTarget&&setSelected(null)}><aside className="va-drawer" role="dialog" aria-modal="true" aria-labelledby="va-drawer-title"><header><div><small>{selected.id?"Карточка видео":"Новое видео"}</small><h2 id="va-drawer-title">{selected.title || "Добавить видео"}</h2></div><button aria-label="Закрыть" onClick={()=>setSelected(null)}>×</button></header>{selected.id ? <><div className="va-player"><iframe src={selected.embedUrl} title={selected.title} allow="fullscreen; encrypted-media; picture-in-picture" allowFullScreen/></div><p>{selected.description || "Описание не добавлено"}</p><a href={selected.url} target="_blank" rel="noreferrer">Открыть источник ↗</a></> : <form onSubmit={addVideo}><label>Ссылка на видео<input name="url" type="url" required placeholder="https://rutube.ru/video/…"/></label><label>Название<input name="title" required/></label><label>Коллекция<select name="collectionId"><option value="">Без коллекции</option>{data.collections.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><p className="va-note">Поддерживаются RUTUBE, YouTube и прямые HTTPS-ссылки. Видео воспроизводится внутри приложения и не копируется на сервер.</p><button className="va-primary">Добавить в видеотеку</button></form>}</aside></div>}
  </section>;
}
