import React, { useEffect, useMemo, useState } from "react";
import "./learner-video.css";
const time=(s)=>s?`${Math.floor(s/60)}:${String(s%60).padStart(2,"0")}`:"Видео";
export function VideoLibrary(){
 const [state,setState]=useState({loading:true,data:null,error:""}),[query,setQuery]=useState(""),[collection,setCollection]=useState(null),[playing,setPlaying]=useState(null);
 useEffect(()=>{let live=true;fetch("/api/v53/videos/library",{credentials:"same-origin"}).then(async r=>{if(!r.ok)throw new Error((await r.json().catch(()=>({}))).detail||"Не удалось загрузить видеотеку");return r.json()}).then(data=>live&&setState({loading:false,data,error:""})).catch(e=>live&&setState({loading:false,data:null,error:e.message}));return()=>{live=false}},[]);
 const videos=state.data?.videos||[],folders=state.data?.collections||[],filtered=useMemo(()=>videos.filter(v=>(!collection||v.collectionId===collection)&&(!query||`${v.title} ${v.description}`.toLowerCase().includes(query.toLowerCase()))),[videos,collection,query]),recent=videos.filter(v=>v.percent>0&&v.percent<100).slice(0,8);
 const card=(v)=><button key={v.id} onClick={()=>setPlaying(v)}><span className="lr-video-thumb">{v.thumbnailUrl?<img src={v.thumbnailUrl} alt=""/>:<i>▶</i>}<em>{time(v.durationSeconds)}</em></span><b>{v.title}</b><small>{v.percent?`${v.percent}% просмотрено`:v.description||"Обучающее видео"}</small>{v.percent>0&&<span className="lr-video-progress"><i style={{width:`${v.percent}%`}}/></span>}</button>;
 return <main className="lr-page lr-video-page"><header className="lr-video-head"><div><span className="lr-eyebrow">Обучающие материалы</span><h1>Видеотека</h1><p>Видео, подобранные для вашей роли и задач.</p></div><label className="lr-video-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск по видеотеке"/></label></header>{state.loading?<section className="lr-resource-state">Загружаем видео…</section>:state.error?<section className="lr-empty"><h2>Не удалось загрузить видеотеку</h2><p>{state.error}</p></section>:<>{!query&&!collection&&recent.length>0&&<section className="lr-video-section"><header><h2>Продолжить просмотр</h2></header><div className="lr-video-rail">{recent.map(card)}</div></section>}<section className="lr-video-section"><header><h2>{collection?folders.find(f=>f.id===collection)?.title:"Папки видеотеки"}</h2>{collection&&<button onClick={()=>setCollection(null)}>Все папки</button>}</header>{collection||query?<div className="lr-video-grid">{filtered.map(card)}</div>:<div className="lr-folder-list">{folders.map(f=><button key={f.id} onClick={()=>setCollection(f.id)}>{f.coverUrl?<img src={f.coverUrl} alt=""/>:<span>▱</span>}<div><b>{f.title}</b><p>{f.description||"Обучающие видео"}</p><small>{f.videoCount} видео</small></div><em>›</em></button>)}</div>}{(collection||query)&&!filtered.length&&<section className="lr-empty"><h2>Видео не найдены</h2><p>Измените запрос или выберите другую папку.</p></section>}</section></>}{playing&&<div className="lr-video-modal" onMouseDown={e=>e.target===e.currentTarget&&setPlaying(null)}><section role="dialog" aria-modal="true" aria-labelledby="lr-video-title"><header><div><small>{playing.provider==="youtube"?"Для YouTube может потребоваться VPN":"Видеотека"}</small><h2 id="lr-video-title">{playing.title}</h2></div><button onClick={()=>setPlaying(null)} aria-label="Закрыть">×</button></header><div><iframe src={playing.embedUrl} title={playing.title} allow="autoplay; fullscreen; encrypted-media; picture-in-picture" allowFullScreen/></div><p>{playing.description}</p></section></div>}</main>}
